version: "3.8"

services:
  db:
    container_name: registrytour-db
    image: mongo
    ports:
      - 27017:27017

  registrytour:
    build:
      context: ./
      args:
        - APP_VERSION=0.0.1-SNAPSHOT
    container_name: registrytour-app
    environment:
      MONGO_URL: mongodb://db:27017/tour
    depends_on:
      - db
    links:
      - db:registrytour-db
    ports:
      - 8080:8080




