version: "3.8"

services:
  app:
    build: .
    environment:
      MONGO_URL: "mongodb://db:27017/tour"
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/registrytour

  db:
    image: mongo